config/routes.rb
Rails.application.routes.draw do
  root to: 'tokens#index'
  
  resources :tokens, only: [:index, :create]
  resource :bot

end

app/models/chat_room.rb
class ChatRoom < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bots_controller.rb
class BotsController < ApplicationController
  def show
    bot_id = '6de4ced8-434b-4803-8b46-32a64b92eb8a'

    vk = VkontakteApi::Client.new(session[:token])
    @messages = vk.messages.get_dialogs(unread: 1, v: 5.37).items.map { |item| item.message.slice(:user_id, :body) }

    @messages.each do |message|
      if (chat_room = ChatRoom.find_by(user_id: message.user_id, bot_id: bot_id))
        bot = IiiApi::Bot.new(chat_room.chat_id)
      else
        bot = IiiApi::Bot.new(bot_id, "6de4ced8-private-room-#{message.user_id}")
        ChatRoom.create(user_id: message.user_id, bot_id: bot_id, chat_id: bot.chat_id)
      end

      message.answer = ActionView::Base.full_sanitizer.sanitize(bot.ask(message.body))
      message.response = vk.messages.send(user_id: message.user_id, message: message.answer, v: 5.37)
    end
  end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  def index
    # https://oauth.vk.com/authorize?client_id=4798482&redirect_uri=http://api.vk.com/blank.html&scope=&display=page&response_type=token
    @url = VK.authorization_url(
      type: :client, 
      scope: %i(photos offline messages friends status wall)
    )
  end

  def create
    session[:token] = params[:token]
    redirect_to bot_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bots/show.html.haml
- if !@messages.blank?
  %pre.prettyprint
    = JSON.pretty_generate(@messages)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title VkBot
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %script{:src => "https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"}
  %body
    = yield
    = debug(params) if Rails.env.development?

app/views/tokens/index.html.haml
%p
  Use url to obtain token:
  = link_to 'VK_app', @url, target: '_blank'

= form_tag(tokens_path) do
  = text_field_tag :token
  = submit_tag 'Submit'